[package]
name = "galvanic-test"
version = "0.1.0"
authors = ["Christopher Bacher <mindsbackyard@gmail.com>"]

[dependencies]
galvanic-mock = { version = "0.1", optional = true }

[features]
galvanic_mock_integration = ["galvanic-mock"]
